/* eslint-disable @typescript-eslint/no-explicit-any */
import { getClient, isContentTypeRegistered, setPageContext } from '@optimizely/cms-sdk';
import { generateCmsMetadata } from '@optimizely/cms-sdk/next';
import { OptimizelyComponent } from '@optimizely/cms-sdk/react/server';
import { PageDataProvider } from '@optimizely/cms-sdk/react/client';
import { notFound } from 'next/navigation';
import type { Metadata } from 'next';
import React from 'react';
import { getPageContent } from '@/getPageContent';
import { pageContextConfig } from '@/pageContext';

/**
 * Controls what happens when a user visits a path that is not generated by `generateStaticParams`
 * See: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams
 */
export const dynamicParams = true;

function removeSlashes(str: string) {
  const str2 = str.startsWith('/') ? str.slice(1) : str;

  return str2.endsWith('/') ? str2.slice(0, -1) : str2;
}

/**
 * Generates static routes at build-time
 * See: https://nextjs.org/docs/app/api-reference/functions/generate-static-params
 */
export async function generateStaticParams() {
  if (!process.env.APPLICATION_HOST) {
    return [];
  }

  // Note: in this sample site, we do not use pagination for querying pages.
  // If a website has more than 100 pages, only 100 will be statically generated
  const query = `
  query GetPosts {
    _Page(limit: 100) {
      items {
        _metadata {
          types
          url {
            base
            default
          }
        }
      }
    }
  }
    `;

  const client = getClient();
  const data = await client.request(query, {});

  return data._Page.items
    .filter((item: any) => {
      if (item?._metadata?.url?.base !== process.env.APPLICATION_HOST) {
        return false;
      }

      const contentType = item?._metadata?.types?.[0];
      if (!contentType) {
        return false;
      }

      const isRegistered = isContentTypeRegistered(contentType);
      return isRegistered;
    })
    .map((item: any) => item?._metadata?.url?.default)
    .filter((path?: string) => typeof path === 'string')
    .map(removeSlashes)
    .filter((path: string) => path !== '')
    .map(
      // Format as required in Next.js
      (path: string) => ({
        slug: path.split('/'),
      }),
    );
}

type Props = {
  params: Promise<{
    slug: string[];
  }>;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const content = await getPageContent(slug);   // React.cache — shared with Page, no extra fetch
  if (!content) return {};
  return generateCmsMetadata(content, {
    titleSuffix: process.env.NEXT_PUBLIC_SITE_NAME ? ` | ${process.env.NEXT_PUBLIC_SITE_NAME}` : '',
  });
}

export default async function Page({ params }: Props) {
  const { slug } = await params;
  const content = await getPageContent(slug);   // cache hit — same request as generateMetadata

  if (!content) {
    notFound();
  }

  const pageData = setPageContext(content, pageContextConfig);

  if (pageData) {
    return (
      <PageDataProvider data={pageData}>
        <OptimizelyComponent content={content as any} />
      </PageDataProvider>
    );
  }

  return <OptimizelyComponent content={content as any} />;
}
