/* eslint-disable @typescript-eslint/no-explicit-any */
import { getClient, isContentTypeRegistered } from '@optimizely/cms-sdk';
import { OptimizelyComponent } from '@optimizely/cms-sdk/react/server';
import { notFound } from 'next/navigation';
import React from 'react';
import { getDictionary, SUPPORTED_LOCALES, DEFAULT_LOCALE } from '@/i18n';
import { AppDictionaryProvider } from '@/components/AppDictionaryProvider';
import HomePage from '@/components/HomePage';

/**
 * Controls what happens when a user visits a path that is not generated by `generateStaticParams`
 * See: https://nextjs.org/docs/app/api-reference/file-conventions/route-segment-config#dynamicparams
 */
export const dynamicParams = true;

function removeSlashes(str: string) {
  const str2 = str.startsWith('/') ? str.slice(1) : str;

  return str2.endsWith('/') ? str2.slice(0, -1) : str2;
}

/**
 * Generates static routes at build-time
 * See: https://nextjs.org/docs/app/api-reference/functions/generate-static-params
 */
export async function generateStaticParams() {
  if (!process.env.APPLICATION_HOST) {
    return [];
  }

  // Note: in this sample site, we do not use pagination for querying pages.
  // If a website has more than 100 pages, only 100 will be statically generated
  const query = `
  query GetPosts {
    _Page(limit: 100) {
      items {
        _metadata {
          types
          url {
            base
            default
          }
        }
      }
    }
  }
    `;

  const client = getClient();
  const data = await client.request(query, {});

  return data._Page.items
    .filter((item: any) => {
      if (item?._metadata?.url?.base !== process.env.APPLICATION_HOST) {
        return false;
      }

      const contentType = item?._metadata?.types?.[0];
      if (!contentType) {
        return false;
      }

      const isRegistered = isContentTypeRegistered(contentType);
      return isRegistered;
    })
    .map((item: any) => item?._metadata?.url?.default)
    .filter((path?: string) => typeof path === 'string')
    .map(removeSlashes)
    .filter((path: string) => path !== '')
    .map(
      // Format as required in Next.js
      (path: string) => ({
        slug: path.split('/'),
      }),
    );
}

type Props = {
  params: Promise<{
    slug: string[];
  }>;
};

export default async function Page({ params }: Props) {
  const { slug } = await params;

  // Determine whether the first segment is a configured locale code.
  // Multi-language:   /de-de/home  → slug[0]='de-de' → locale='de-de', path='/home'
  // Single-language:  /about       → slug[0]='about'  → locale='en-us', path='/about'
  const hasLocalePrefix = SUPPORTED_LOCALES.includes(slug[0]);
  const locale = hasLocalePrefix ? slug[0] : DEFAULT_LOCALE;
  const pageSlugs = hasLocalePrefix ? slug.slice(1) : slug;

  // /en-us/ or /zh-cn/ with no page slug → locale-prefixed home page.
  // CMS has no content at bare locale paths, so serve the home page component
  // in the requested locale rather than attempting a doomed CMS fetch.
  if (pageSlugs.length === 0) {
    return <HomePage locale={locale} />;
  }

  // getDictionary creates a fresh instance per request — no shared mutable state.
  const dict = await getDictionary(locale);

  const path = `/${pageSlugs.join('/')}`;
  const client = getClient();
  const content = await client.getContentByPath(`${path}/`);

  if (content.length === 0) {
    notFound();
  }

  return (
    <AppDictionaryProvider locale={locale}>
      <nav>
        <a href='/'>{dict.t('nav.home')}</a>
        {' · '}
        <a href={`/${locale}/blog`}>{dict.t('nav.blog')}</a>
        {' · '}
        <a href={`/${locale}/contact`}>{dict.t('nav.contact')}</a>
      </nav>
      <OptimizelyComponent content={content[0]} />
    </AppDictionaryProvider>
  );
}
